#!/bin/sh

sudo pkg install -y rlwrap git taskwarrior tig tor ecl
sudo useradd -m solene
sudo chown solene /home/solene
install -d -o solene -m 700 /home/solene/.ssh
install -d -o solene -m 700 /home/solene/dev/

cd /home/solene/dev
sudo su solene -c 'git clone bitreich.org/clic'

