#!/bin/sh
mkdir -p /tmp/results
cp -f subdomains_resolved.txt /tmp/

# install httpx x86_64 xbps package
#xbps-install -Suy xtools
#echo "Y" | xdowngrade *.xbps

# install httpx ARM binary
ls /usr/local/bin/httpx || wget https://github.com/projectdiscovery/httpx/releases/download/v1.0.2/httpx_1.0.2_linux_arm64.tar.gz -qO - | tar -xzvf - -C /usr/local/bin/ httpx

#cat subdomains_resolved.txt | /usr/local/bin/httpx -ports 80,8000,8008,8800,8080,8880,8888,443,4433,8443 -status-code -mc 200,403 -silent -title -follow-redirects -o /tmp/results/httpx_200_403.txt
