#!/bin/sh

sudo sh iptables.sh && sudo iptables-save > /etc/iptables/iptables.rules
#cat iptables.sh

cat >> /etc/rc.local << EOF
[ -e /etc/iptables/iptables.rules ] && {
  iptables-restore /etc/iptables/iptables.rules
}
EOF


