#!/bin/sh
# n0
# file: script
# description: build and install literrbox irc logger on alpine
# usage: drist -p root@server
# a110w

apk update
apk add sqlite sqlite-dev libressl libressl-dev build-base ctags git

git clone https://git.causal.agency/litterbox
cd litterbox
./configure && {
  make
  make install
}

mkdir -p ~/.local/share/litterbox
