#!/bin/sh
# change version to update
VERSION=5.27.2

apk update
apk add build-base zlib-dev monit-openrc

wget https://mmonit.com/monit/dist/monit-$VERSION.tar.gz & {
  tar xzvf monit-$VERSION.tar.gz
  cd monit-$VERSION
  ./configure --without-pam --without-ipv6 --without-ssl
  make && make install
  } 

cp monitrc /etc/monitrc
chmod 0700 /etc/monitrc
monit -t && {
  rc-update add monit
  rc-service start monit
}

