#!/bin/sh

# update system
sudo xbps-install -Suy

# install common utils
sudo xbps-install -y curl libcurl-devel wget gcc make cmake git strace neovim tmux jq fish-shell at doctl

# self destruct
sudo ln -sf /etc/sv/at /var/service/
doctl auth init -t $(cat api)
# read timer < explode-timer
sleep 5 && echo "doctl compute droplet delete -f $(curl -s http://169.254.169.254/metadata/v1/id)" | at now + ${timer:-5 minutes}
