#!/bin/sh
# n0
# File: script (drist playbook)
# Description: A playbook to deploy my piirc configuration to a Raspberry Pi (or lxd container) running Void
# a110w

HOSTNAME=piirc
USER=void
HOME=/home/$USER

configure_hostname(){
	echo $HOSTNAME > /etc/hostname
	hostname $HOSTNAME
}

install_pkgs(){
	xbps-install -Syu tor tmux weechat firejail
	ln -sf /usr/bin/firejail /usr/local/bin/weechat
}

configure_user(){
	# bashrc
	echo "PATH=/usr/local/bin:$PATH" >> $HOME/.bashrc
	
	# tmux
	cp tmux.conf $HOME/.tmux.conf
	mkdir -p $HOME/.config/tmux
	tar -C $HOME/.config/tmux -xzvf tmux_backup_latest.tar.gz
	
	# weechat
	mkdir $HOME/.weechat
	tar -C $HOME/.weechat -xzvf weechat_backup_latest.tar.gz
	cp start_weechat.sh $HOME
}

configure_tor(){
	mkdir -p /etc/tor
	cat <<- EOF > /etc/tor/torrc
		SocksPort 127.0.0.1:9050
		SocksPort 127.0.0.1:9052
		SocksPort 127.0.0.1:9053
		SocksPort 127.0.0.1:9054
		Log notice file /var/log/tor/notices.log
		DataDirectory /var/lib/tor
		ControlPort 9051
		CookieAuthentication 1
		User tor
	EOF

	mkdir -p /var/log/tor
	touch /var/log/tor/notices.log
	chown -R tor:tor /var/log/tor
	chmod 644 /var/log/tor/notices.log

	ln -sf /etc/sv/tor /var/service/
}

fix_ownerships(){
	chown -R $USER:$USER $HOME
	chown tor:tor /etc/tor/torrc
}

configure_hostname
install_pkgs
configure_user
configure_tor
fix_ownerships
