#!/bin/sh
# n0
# File: script ( drist playbook )
# Description: Deploy my irc client configuration to a Raspberry Pi running Void
# a110w

# Vars
HOSTNAME=piirc
USER=void
HOME=/home/$USER

# Set Hostname
echo $HOSTNAME > /etc/hostname
hostname $HOSTNAME

# Configure Tor Daemon
mkdir -p /etc/tor
cat <<- EOF > /etc/tor/torrc
	SocksPort 127.0.0.1:9050
	SocksPort 127.0.0.1:9052
	SocksPort 127.0.0.1:9053
	SocksPort 127.0.0.1:9054
	Log notice syslog
	DataDirectory /var/lib/tor
	ControlPort 9051
	CookieAuthentication 1
	User tor
EOF

# Enable Tor Daemon
ln -sf /etc/sv/tor /var/service/
sleep 10 # give time for circuits to come up. no rush

# Configure XBPS Tor Mirror
cat <<- EOF > /etc/xbps.d/00-repository-main.conf
	repository=http://lysator7eknrfl47rlyxvgeamrv7ucefgrrlhk7rouv3sna25asetwid.onion/pub/voidlinux/current/aarch64
EOF

cat <<- EOF > /etc/profile.d/socksproxy.sh
	#!/bin/sh
	export SOCKS_PROXY="socks5://127.0.0.1:9050"
EOF

# Install Packages
SOCKS_PROXY="socks5://127.0.0.1:9050" xbps-install -Syu tor tmux weechat firejail

# Copy User Configurations
# bashrc
echo "PATH=/usr/local/bin:$PATH" >> $HOME/.bashrc
# weechat
#mkdir $HOME/.weechat
#tar xzf weechat.tar.gz -C $HOME/.weechat
# tmux
#cp tmux.conf $HOME/.tmux.conf
#tar xzf tmux_theme.tar.gz -C $HOME

# Firejail weechat
ln -sf /usr/bin/firejail /usr/local/bin/weechat

# Fix Ownerships
chown -R $USER:$USER $HOME
chown tor:tor /etc/tor/torrc
